---
- name: Ensure python-pip is installed
  apt:
    name: "{{ dehydrated_pip_package }}"
  when: dehydrated_install_pip

- name: Install dns-lexicon
  pip:
    name: "dns-lexicon{{ '==' ~ dehydrated_lexicon_dns_version if dehydrated_lexicon_dns_version is defined else '' }}"
    executable: "{{ dehydrated_pip_executable|default(omit) }}"

- name: Copy hook script
  copy:
    dest: /etc/dehydrated/hooks.d/01lexicon
    src: 01lexicon
    owner: root
    group: root
    mode: "0700"
